queue:
  container_name: queue
  restart: always
  image: schickling/beanstalkd
mysql:
  container_name: mysql
  restart: always
  # image: mysql
  image: mysql:5
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=homestead
    - MYSQL_USER=homestead
    - MYSQL_PASSWORD=secret
  volumes:
    - /Users/kurota/Desktop/Devlopment/mysqldata/mysql:/var/lib/mysql
    # for mysql 8.0 above
    # mysql -u root -p
    # secret
    # ALTER USER 'homestead'@'%' IDENTIFIED WITH mysql_native_password BY 'secret';

php:
  container_name: php
  restart: always
  image: php:fpm-alpine
  # image: kyjita/php_alpine_pdo_composer:latest
  links:
    - mysql:mysql
    - queue:queue
    - redis:redis
  environment:
    - DB_HOST=mysql
    - DB_DATABASE=homestead
    - DB_USERNAME=homestead
    - DB_PASSWORD=secret
    - REDIS_HOST=redis
    - SESSION_DRIVER=redis
    - CACHE_DRIVER=redis
    - BEANSTALKD_HOST=queue
    - REDIS_PORT=6379
    - MYSQL_VERSION=latest
  volumes:
    - ./:/var/www/laravel/
  working_dir: /var/www/laravel

nginx:
  container_name: nginx
  restart: always
  image: nginx:alpine
  ports:
    - "8080:80"
  links:
    - php:php
  volumes_from:
    - php
  volumes:
    - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
redis:
  image: redis:alpine
  container_name: redis
  ports:
    - 6379:6379
  # expose:
  #   - '6379'
websocket:
  container_name: websocket
  image: kyjita/websocket
  restart: always
  ports:
    - 3000:3000
  links:
    - redis
  volumes:
    - ./app.js:/srv/app.js
    - ./test.html:/srv/test.html

  # command: node /srv/app.js
